const src = require("fs").readFileSync("scripts/source.c").toString();
const enumSet = {
    "ALPHA_TEST": true,
    "AUTO_NORMAL": true,
    "BLEND": true,
    "CLIP_PLANE": true,
    "COLOR_LOGIC_OP": true,
    "COLOR_MATERIAL": true,
    "COLOR_SUM": true,
    "COLOR_TABLE": true,
    "CONVOLUTION_1D": true,
    "CONVOLUTION_2D": true,
    "CULL_FACE": true,
    "DEPTH_TEST": true,
    "DITHER": true,
    "FOG": true,
    "HISTOGRAM": true,
    "INDEX_LOGIC_OP": true,
    "LIGHT": true,
    "LIGHTING": true,
    "LINE_SMOOTH": true,
    "LINE_STIPPLE": true,
    "MAP1_COLOR_4": true,
    "MAP1_INDEX": true,
    "MAP1_NORMAL": true,
    "MAP1_TEXTURE_COORD_1": true,
    "MAP1_TEXTURE_COORD_2": true,
    "MAP1_TEXTURE_COORD_3": true,
    "MAP1_TEXTURE_COORD_4": true,
    "MAP1_VERTEX_3": true,
    "MAP1_VERTEX_4": true,
    "MAP2_COLOR_4": true,
    "MAP2_INDEX": true,
    "MAP2_NORMAL": true,
    "MAP2_TEXTURE_COORD_1": true,
    "MAP2_TEXTURE_COORD_2": true,
    "MAP2_TEXTURE_COORD_3": true,
    "MAP2_TEXTURE_COORD_4": true,
    "MAP2_VERTEX_3": true,
    "MAP2_VERTEX_4": true,
    "MINMAX": true,
    "MULTISAMPLE": true,
    "NORMALIZE": true,
    "POINT_SMOOTH": true,
    "POINT_SPRITE": true,
    "POLYGON_OFFSET_FILL": true,
    "POLYGON_OFFSET_LINE": true,
    "POLYGON_OFFSET_POINT": true,
    "POLYGON_SMOOTH": true,
    "POLYGON_STIPPLE": true,
    "POST_COLOR_MATRIX_COLOR_TABLE": true,
    "POST_CONVOLUTION_COLOR_TABLE": true,
    "RESCALE_NORMAL": true,
    "SAMPLE_ALPHA_TO_COVERAGE": true,
    "SAMPLE_ALPHA_TO_ONE": true,
    "SAMPLE_COVERAGE": true,
    "SEPARABLE_2D": true,
    "SCISSOR_TEST": true,
    "STENCIL_TEST": true,
    "TEXTURE_1D": true,
    "TEXTURE_2D": true,
    "TEXTURE_3D": true,
    "TEXTURE_CUBE_MAP": true,
    "TEXTURE_GEN_Q": true,
    "TEXTURE_GEN_R": true,
    "TEXTURE_GEN_S": true,
    "TEXTURE_GEN_T": true,
    "VERTEX_PROGRAM_POINT_SIZE": true,
    "VERTEX_PROGRAM_TWO_SIDE": true,
}

const lines = src.split(/\r?\n/);
for (const line of lines) {
    const sub = line.slice(11, line.length);
    const temp = sub.split(/\s+/);
    const name = temp[0];
    const value = temp[1];
    if (enumSet[name]) {
        console.log(`${name} = ${value},`);
    }
}